// Constants for Chat
const GET_MESSAGES = 'GET_MESSAGES';
const ADD_MESSAGE = 'ADD_MESSAGE';
const SEND_MESSAGE = 'SEND_MESSAGE';
const INITIATE_CHAT = 'INITIATE_CHAT';

export default { GET_MESSAGES, ADD_MESSAGE, SEND_MESSAGE, INITIATE_CHAT };
