// Constants for Chat
const GET_CONVERSATION = 'GET_CONVERSATION';
const ADD_MESSAGE = 'ADD_MESSAGE';
const SEND_MESSAGE = 'SEND_MESSAGE';
const INITIATE_CHAT = 'INITIATE_CHAT';

export default { GET_CONVERSATION, ADD_MESSAGE, SEND_MESSAGE, INITIATE_CHAT };
